name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: zulu@1.8
    - uses: coursier/cache-action@v6
    - run: |
        sbt +test

